# Query.srv
# Service for querying robot episodic memory

# Request
string question

---

# Response
bool success
string type
string text
string binary
float64[] position
float64 orientation
float64 time
float64 duration
string error
