services:
  # ===== AMD64 =====
  remembr:
    image: cuda12.9.1:humble-uv-nvm
    build: .
    container_name: remembr
    volumes:
      - .:/root/remembr
      - /tmp/.X11-unix:/tmp/.X11-unix
      - uv-cache:/root/.cache/uv
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    working_dir: /root/remembr
    ipc: host
    privileged: true
    tty: true

  remembr-gpu:
    container_name: remembr-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, graphics]
    extends:
      service: remembr
    profiles:
      - gpu

  remembr-qdrant:
    image: qdrant/qdrant:latest
    container_name: remembr-qdrant
    volumes:
      - ./src/qdrant/db:/qdrant/storage
    network_mode: host

  # ===== Jetson ARM64 =====
  remembr-jetson:
    image: cudnn8.9-jetson:humble-uv-nvm
    build:
      args:
        BASE_IMAGE: dustynv/cudnn:8.9-r36.2.0
    container_name: remembr-jetson
    volumes:
      - .:/root/remembr
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/argus_socket:/tmp/argus_socket
      - ~/.Xauthority:/root/.Xauthority
      - uv-cache:/root/.cache/uv
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/root/.Xauthority
    network_mode: host
    working_dir: /root/remembr
    ipc: host
    privileged: true
    profiles:
      - jetson
    runtime: nvidia
    tty: true

volumes:
  uv-cache: